### ISSUE TITLE
[Quality] Implement Release Management

### ISSUE THREAD

**Issue by aj-geddes** [aj-geddes/python-mcp-server-template#27]
## Overview

As part of the Repository Quality Implementation Plan, we need to implement a release management setup for the Python MCP Server Template repository. This will ensure consistent and automated versioning, changelogs, and release notes.

### 1. Semantic Release Configuration

Add a semantic release configuration file at `.releaserc.json`:

```json
{
  "branches": ["main", "master"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/github",
    ["@semantic-release/git", {
      "assets": ["CHANGELOG.md", "package.json"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]
  ]
}
```

### 2. Release Workflow

Create a release workflow at `.github/workflows/release.yml`:

```yaml
name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git
        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
```

### 3. Initial CHANGELOG.md

Create or update the CHANGELOG.md file with an initial structure:

```markdown
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Initial repository setup
- FastMCP server implementation
- Basic MCP tools (echo, file operations)
- Docker configuration
- CI/CD workflows
```

### 4. Version Tagging in Python Code

Update the version definition in the main module:

1. Add a version file at `mcp_server/version.py`:

```python
"""Version information."""

__version__ = "0.1.0"
```

2. Import and use the version in the main module:

```python
from mcp_server.version import __version__

# Use in application
app = FastAPI(title="MCP Server", version=__version__)
```

### 5. Version Management in pyproject.toml

Update `pyproject.toml` to include version information:

```toml
[tool.poetry]
name = "python-mcp-server-template"
version = "0.1.0"
description = "A production-ready MCP server template using FastMCP framework"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/aj-geddes/python-mcp-server-template"

[tool.poetry.dependencies]
python = "^3.10"
# ... other dependencies
```

### 6. Commit Message Guidelines

Add a section to CONTRIBUTING.md about commit message guidelines:

```markdown
## Commit Message Guidelines

We follow the [Conventional Commits](https://www.conventionalcommits.org/) specification for commit messages:

```
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

Types:
- `feat`: A new feature
- `fix`: A bug fix
- `docs`: Documentation changes
- `style`: Code style changes (formatting, etc.)
- `refactor`: Code refactoring
- `test`: Adding or improving tests
- `chore`: Maintenance tasks

Examples:
- `feat(api): add new endpoint for file uploads`
- `fix: resolve issue with file path validation`
- `docs: update README with configuration options`
- `chore(deps): update dependencies`
```

### 7. GitHub Release Configuration

Ensure releases on GitHub include:

1. Proper tags (v1.0.0, v1.1.0, etc.)
2. Release notes generated from changelog
3. Asset uploads (if applicable)

## Acceptance Criteria

1. Semantic Release is properly configured and works with CI/CD
2. Releases are automatically created when merging to the main branch
3. Version information is consistently managed across the repository
4. CHANGELOG.md is automatically updated during the release process
5. Contributors understand the commit message guidelines

## Resources

- [Semantic Release Documentation](https://semantic-release.gitbook.io/semantic-release/)
- [Conventional Commits](https://www.conventionalcommits.org/)
- [GitHub Actions for Releases](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release)
- [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)

## Related Issues

- #24 Implement CI/CD Workflow
